apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
  labels:
    app: nginx-exporter
spec:
  type: NodePort
  ports:
  - port: 9113
    targetPort: 9113
    protocol: TCP
  selector:
    app: nginx-exporter