apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node1'
        static_configs:
          - targets: ['nginx-exporter-service.node1.svc.cluster.local:9113']
      - job_name: 'node2'
        static_configs:
          - targets: ['nginx-exporter-service.node2.svc.cluster.local:9113']
      - job_name: 'node3'
        static_configs:
          - targets: ['nginx-exporter-service.node3.svc.cluster.local:9113']