apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: monitoring
data:
  prometheus.yml: |

    scrape_configs:
      - job_name: nginxplus-target
        honor_timestamps: true
        scrape_interval: 5s
        scrape_timeout: 5s
        metrics_path: /metrics
        scheme: http
        follow_redirects: true
        static_configs:
          - targets: ['10.110.0.1:80']
          - targets: ['10.110.0.2:80']
          - targets: ['10.110.0.3:80']
