apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - nodePort: 30016
      port: 8080
      targetPort: 8080
      protocol: TCP
      name: nodejs
  type: NodePort
