apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nginx-api
  type: NodePort