apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
  name: nginx-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:    
      - image: tomcat     
        name: tomcat
        ports:
        - containerPort: 8080              
      - image: nginxstore/nginxplus:nginx-plus
        name: nginx-proxy
        ports:
        - containerPort: 80
        - containerPort: 9113
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/metric.conf
          subPath: metric.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
