apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }

    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        access_log  /var/log/nginx/access.log  main;
    
        sendfile        on;
        #tcp_nopush     on;
    
        keepalive_timeout  65;
    
        #gzip  on;
    
        include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |
    upstream tomcat {
      zone tomcat 32k;
      server localhost:8080;
    }

    server {
        listen       80;
    
        #access_log  /var/log/nginx/host.access.log  main;
    
        location / {
            proxy_pass http://tomcat;
            status_zone backend;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    
    }
  metric.conf: |
    server {
        listen 9113;

        location /api {
          api write=on;
        }

        location = /dashboard.html {
            root   /usr/share/nginx/html;
        }

    }
