apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx-proxy
  - port: 9113
    targetPort: 9113
    protocol: TCP
    name: metric
  selector:
    app: tomcat
