apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 2s # Prometheus가 메트릭을 수집하는 기본 간격
    scrape_configs:
      - job_name: 'nginx-plus-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_proxy]
            action: keep
            regex: nginx
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: nginx-plus
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: pod
